---
name: Auto-approve Renovate PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    name: Auto-approve Renovate PRs
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'

    steps:
      - name: Setup | Create access token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
